//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Yarng.rc
//
#define IDR_MANIFEST                    1
#define ID_BUTTON_RANDOM                3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_YARNG_DIALOG                102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_DEFAULT_SETTINGS            105
#define IDS_PROBABILITY_TABLE           106
#define IDS_LNG_LOAD                    107
#define IDS_LNG_SAVE                    108
#define IDS_GENERATE                    109
#define IDS_ABOUT                       110
#define IDS_HISTORY                     111
#define IDS_HOWTO                       112
#define IDS_EXIT                        113
#define IDS_INDICATOR_TIME              114
#define IDS_INDICATOR_NISH              115
#define IDS_INDICATOR_DESCRIPT          115
#define IDS_PRODUCTNAME                 116
#define IDS_PRODUCTVERSION              117
#define IDR_MAINFRAME                   128
#define IDI_ICON_MFC7                   129
#define IDI_ICON_MSVC7                  130
#define IDI_ICON_MFC6                   131
#define IDI_ICON_MSVC6                  132
#define IDD_DIALOG_HISTORY              134
#define IDD_DIALOG_HOWTO                135
#define IDD_DIALOG_PROBABILITY          136
#define IDI_ICON_GENERATE               142
#define IDI_ICON_EXIT                   144
#define IDI_ICON_ABOUT                  146
#define IDI_ICON_HISTORY                147
#define IDI_ICON_DEFAULTSETTINGS        148
#define IDI_ICON_LOAD                   149
#define IDI_ICON_SAVE                   150
#define IDI_ICON_HOME                   151
#define IDI_ICON_PROBABILITYTABLE       152
#define IDI_ICON_HOWTO                  153
#define IDI_ICON_RANDOM                 154
#define IDI_ICON_CANCEL                 156
#define IDI_ICON_OK                     157
#define IDI_ICON_WEB1                   159
#define IDI_ICON_WEB2                   160
#define IDI_ICON_WIN16                  161
#define IDI_ICON_BACK                   162
#define IDI_ICON_BLANK                  163
#define IDI_ICON_FORWARD                164
#define IDI_ICON_GENERATE2              165
#define IDI_ICON_HELP2                  166
#define IDI_ICON_HELP                   167
#define IDI_ICON_LEFT                   168
#define IDI_ICON_MAC2                   169
#define IDI_ICON_MAIL2                  170
#define IDI_ICON_MAIL3                  171
#define IDI_ICON_MAIL                   172
#define IDI_ICON_OPEN2                  173
#define IDI_ICON_COPY                   174
#define IDI_ICON_PRINT2                 175
#define IDI_ICON_PRINT                  176
#define IDI_ICON_REDO                   177
#define IDI_ICON_REFRESH                178
#define IDI_ICON_RIGHT                  179
#define IDI_ICON_EXPORT                 181
#define IDI_ICON_COPY2                  182
#define IDD_DIALOG_EXPORT               183
#define IDC_EDIT_GENERATED_NAMES        1000
#define IDC_EDIT_MIN_LEN_OF_NAMES       1001
#define IDC_EDIT_MAX_LEN_OF_NAMES       1002
#define IDC_EDIT_NUMB_OF_NAMES          1003
#define IDS_EDIT_NUMB_OF_NAMES          1003
#define IDC_BUTTON_GENERATE             1004
#define IDS_EDIT_MIN_LEN_OF_NAMES       1004
#define IDS_EDIT_VOWELS                 1005
#define IDS_EDIT_CONSONANTS             1006
#define IDC_BUTTON_ABOUT                1007
#define IDS_COMBO_LANGUAGE              1007
#define IDC_BUTTON_HISTORY              1008
#define IDS_EDIT_MAX_LEN_OF_NAMES       1008
#define IDC_BUTTON_HOWTO                1009
#define IDS_CLEAR                       1009
#define IDC_BUTTON_EXIT                 1010
#define IDS_EXPORT                      1010
#define IDS_PRINT                       1011
#define IDC_EDIT_HISTORY                1012
#define IDS_COPY                        1012
#define IDC_EDIT_HOWTO                  1013
#define IDC_EDIT_VOWELS                 1014
#define IDC_EDIT_CONSONANTS             1015
#define IDC_BUTTON_DEFAULT_SETTINGS     1016
#define IDC_EDIT_PROBABILITY_A          1017
#define IDC_EDIT_PROBABILITY_B          1018
#define IDC_EDIT_PROBABILITY_C          1019
#define IDC_EDIT_PROBABILITY_D          1020
#define IDC_EDIT_PROBABILITY_E          1021
#define IDC_EDIT_PROBABILITY_F          1022
#define IDC_EDIT_PROBABILITY_G          1023
#define IDC_EDIT_PROBABILITY_I          1024
#define IDC_EDIT_PROBABILITY_J          1025
#define IDC_EDIT_PROBABILITY_K          1026
#define IDC_EDIT_PROBABILITY_M          1027
#define IDC_EDIT_PROBABILITY_N          1028
#define IDC_EDIT_PROBABILITY_O          1029
#define IDC_EDIT_PROBABILITY_P          1030
#define IDC_EDIT_PROBABILITY_Q          1031
#define IDC_EDIT_PROBABILITY_R          1032
#define IDC_EDIT_PROBABILITY_S          1033
#define IDC_EDIT_PROBABILITY_T          1034
#define IDC_EDIT_PROBABILITY_U          1035
#define IDC_EDIT_PROBABILITY_V          1036
#define IDC_EDIT_PROBABILITY_W          1037
#define IDC_EDIT_PROBABILITY_X          1038
#define IDC_EDIT_PROBABILITY_Y          1039
#define IDC_EDIT_PROBABILITY_Z          1040
#define IDC_EDIT_PROBABILITY_H          1041
#define IDC_EDIT_PROBABILITY_L          1042
#define IDC_STATIC_PROBABILITY_A        1043
#define IDC_STATIC_PROBABILITY_B        1044
#define IDC_STATIC_PROBABILITY_C        1045
#define IDC_STATIC_PROBABILITY_D        1046
#define IDC_STATIC_PROBABILITY_E        1047
#define IDC_STATIC_PROBABILITY_F        1048
#define IDC_STATIC_PROBABILITY_H        1049
#define IDC_STATIC_PROBABILITY_G        1050
#define IDC_STATIC_PROBABILITY_I        1051
#define IDC_STATIC_PROBABILITY_J        1052
#define IDC_STATIC_PROBABILITY_K        1053
#define IDC_STATIC_PROBABILITY_L        1054
#define IDC_STATIC_PROBABILITY_M        1055
#define IDC_STATIC_PROBABILITY_N        1056
#define IDC_STATIC_PROBABILITY_O        1057
#define IDC_STATIC_PROBABILITY_P        1058
#define IDC_STATIC_PROBABILITY_Q        1059
#define IDC_STATIC_PROBABILITY_R        1060
#define IDC_STATIC_PROBABILITY_S        1061
#define IDC_STATIC_PROBABILITY_T        1062
#define IDC_STATIC_PROBABILITY_U        1063
#define IDC_STATIC_PROBABILITY_V        1064
#define IDC_STATIC_PROBABILITY_W        1065
#define IDC_STATIC_PROBABILITY_X        1066
#define IDC_STATIC_PROBABILITY_Y        1067
#define IDC_STATIC_PROBABILITY_Z        1068
#define IDC_BUTTON_PROBABILITY_TABLE    1069
#define IDC_EDIT_ABOUT                  1070
#define IDC_COMBO_LANGUAGE              1071
#define IDC_BUTTON_LNG_LOAD             1073
#define IDC_BUTTON_LNG_SAVE             1074
#define IDC_BUTTON_EXPORT               1075
#define IDC_EMAILLINK                   1076
#define IDC_BUTTON_CLEAR                1076
#define IDC_WWWLINK1                    1077
#define IDC_WWWLINK2                    1078
#define IDC_BUTTON_COPY                 1078
#define IDC_SPIN_NUMB_OF_NAMES          1079
#define IDC_SPIN_EDIT_MIN_LEN_OF_NAMES  1080
#define IDC_SPIN_EDIT_MAX_LEN_OF_NAMES  1081
#define IDC_BUTTON_PRINT                1082
#define IDC_PROGRESS_GENERATE           1083
#define IDC_RADIO_EXPORT_TXT            1084
#define IDC_RADIO_EXPORT_CSV            1085
#define IDC_RADIO_EXPORT_HTM            1086
#define IDC_BUTTON1                     1087
#define IDC_RADIO_EXPORT_SLK            1088
#define IDC_CHECK_EXPORT_LINEFEEDS      1089
#define IDC_CHECK_EXPORT_CREATOR        1090

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1090
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
